# Generated by Django 2.2.5 on 2021-10-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211019_0012'),
        ('store', '0012_seller'),
    ]

    operations = [
    ]
