# Generated by Django 2.2.5 on 2021-10-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_merge_20211021_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='addressProof',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(default='not verified', max_length=50),
        ),
    ]
