# Generated by Django 2.2.5 on 2021-10-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20211022_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='addressProof',
            new_name='gstDocument',
        ),
        migrations.AddField(
            model_name='seller',
            name='panCard',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
