# Generated by Django 2.2.14 on 2021-11-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpayorderid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='Kart-O-City/uploads/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(upload_to='Kart-O-City/uploads/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(upload_to='Kart-O-City/uploads/products/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gstDocument',
            field=models.FileField(null=True, upload_to='Kart-O-City/uploads/userdocuments'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='panCard',
            field=models.FileField(null=True, upload_to='Kart-O-City/uploads/userdocuments'),
        ),
    ]
