# Generated by Django 2.2.14 on 2021-11-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20211110_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpaypaymentid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
