# Generated by Django 2.2.14 on 2021-11-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_razorpaypaymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gstDocument',
            field=models.FileField(null=True, upload_to='HAAw60mUKMN8z9ewjHvcIOMUQMXX6lMr/uploads/userdocuments'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='panCard',
            field=models.FileField(null=True, upload_to='HAAw60mUKMN8z9ewjHvcIOMUQMXX6lMr/uploads/userdocuments'),
        ),
    ]
